<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Enums
    |--------------------------------------------------------------------------
    |
    | Here we define config backed enums
    |
    */
    'factfind' => [
       'basic-details' => [
           'personal-details',
           'health-details',
           'address-and-contact-details',
           'family',
           'employment-details',
       ],
       'income-and-expenditure' => [

       ],
       'assets' => [

       ],
       'liabilities' => [

       ],
       'risk' => [

       ],
    ],
    'client' => [
        'title' => [
            0 => 'Miss',
            1 => 'Mr',
            2 => 'Mrs',
            3 => 'Ms',
            4 => 'Admiral',
            5 => 'Air Commodore',
            6 => 'Air Vice Marshall',
            7 => 'Archdeacon',
            8 => 'Baron',
            9 => 'Baroness',
            10 => 'Bishop',
            11 => 'Brigadier',
            12 => 'Canon',
            13 => 'Captain',
            14 => 'Colonel',
            15 => 'Commander',
            16 => 'Commodore',
            17 => 'Corporal',
            18 => 'Count',
            19 => 'Countess',
            20 => 'Dame',
            21 => 'Deacon',
            22 => 'Deaconess',
            23 => 'Dr',
            24 => 'Duchess',
            25 => 'Duke',
            26 => 'Father',
            27 => 'Flight Lieutenant',
            28 => 'General',
            29 => 'Group Captain',
            30 => 'Judge',
            31 => 'Lady',
            32 => 'Lance Corporal',
            33 => 'Lieutenant',
            34 => 'Lieutenant Colonel',
            35 => 'Lieutenant Commander',
            36 => 'Lord',
            37 => 'Madam',
            38 => 'Major',
            39 => 'Major General',
            40 => 'Master',
            41 => 'Monsignor',
            42 => 'Mx',
            43 => 'Other',
            44 => 'Pastor',
            45 => 'Prince',
            46 => 'Princess',
            47 => 'Private',
            48 => 'Professor',
            49 => 'Rabbi',
            50 => 'Rear Admiral',
            51 => 'Reverend',
            52 => 'Reverend Doctor',
            53 => 'Right Honourable',
            54 => 'Right Honourable Lord',
            55 => 'Right Reverend',
            56 => 'Second Lieutenant',
            57 => 'Sergeant',
            58 => 'Sheriff',
            59 => 'Sir',
            60 => 'Sister',
            61 => 'Squadron Leader',
            62 => 'Staff Sergeant',
            63 => 'Surgeon Captain',
            64 => 'The Earl of',
            65 => 'The Honourable',
            66 => 'The Reverend Canon',
            67 => 'Trooper',
            68 => 'Venerable',
            69 => 'Very Reverend',
            70 => 'Viscount',
            71 => 'Viscountess',
            72 => 'Wing Commander'
        ],
        'gender' => [
            0 => 'Unspecified',
            1 => 'Male',
            2 => 'Female'
        ],
        'marital_status' =>[
            0 => 'Single',
            1 => 'Engaged',
            2 => 'Married',
            3 => 'Civil Partner',
            4 => 'Dissolved Civil Partner',
            5 => 'Surviving Civil Partner',
            6 => 'Divorced',
            7 => 'Separated',
            8 => 'Widowed',
            9 => 'Living Together',
            10 => 'Unknown'
        ],
        'nationality' => [
            0 => 'British',
            1 => 'English',
            2 => 'Manx',
            3 => 'Northern Irish',
            4 => 'Scottish',
            5 => 'Welsh',
            6 => 'Other',
            7 => 'Afghan',
            8 => 'Albanian',
            9 => 'Algerian',
            10 => 'American',
            11 => 'Andorran',
            12 => 'Angolan',
            13 => 'Antiguans',
            14 => 'Argentinean',
            15 => 'Armenian',
            16 => 'Australian',
            17 => 'Austrian',
            18 => 'Azerbaijani',
            19 => 'Bahamian',
            20 => 'Bahraini',
            21 => 'Bangladeshi',
            22 => 'Barbadian',
            23 => 'Barbudans',
            24 => 'Batswana',
            25 => 'Belarusian',
            26 => 'Belgian',
            27 => 'Belizean',
            28 => 'Beninese',
            29 => 'Bermudian',
            30 => 'Bhutanese',
            31 => 'Bolivian',
            32 => 'Bosnian',
            33 => 'Brazilian',
            34 => 'Bruneian',
            35 => 'Bulgarian',
            36 => 'Burkinabe',
            37 => 'Burmese',
            38 => 'Burundian',
            39 => 'Cambodian',
            40 => 'Cameroonian',
            41 => 'Canadian',
            42 => 'Cape Verdean',
            43 => 'Central African',
            44 => 'Chadian',
            45 => 'Chilean',
            46 => 'Chinese',
            47 => 'Colombian',
            48 => 'Comoran',
            49 => 'Congolese',
            50 => 'Costa Rican',
            51 => 'Croatian',
            52 => 'Cuban',
            53 => 'Cypriot',
            54 => 'Czech',
            55 => 'Danish',
            56 => 'Djibouti',
            57 => 'Dominican',
            58 => 'Dutch',
            59 => 'East Timorese',
            60 => 'Ecuadorean',
            61 => 'Egyptian',
            62 => 'Emirian',
            63 => 'Equatorial Guinean',
            64 => 'Eritrean',
            65 => 'Estonian',
            66 => 'Ethiopian',
            67 => 'Fijian',
            68 => 'Filipino',
            69 => 'Finnish',
            70 => 'French',
            71 => 'Gabonese',
            72 => 'Gambian',
            73 => 'Georgian',
            74 => 'German',
            75 => 'Ghanaian',
            76 => 'Greek',
            77 => 'Grenadian',
            78 => 'Guatemalan',
            79 => 'Guinea-Bissauan',
            80 => 'Guinean',
            81 => 'Guyanese',
            82 => 'Haitian',
            83 => 'Herzegovinian',
            84 => 'Honduran',
            85 => 'Hungarian',
            86 => 'Icelander',
            87 => 'I-Kiribati',
            88 => 'Indian',
            89 => 'Indonesian',
            90 => 'Iranian',
            91 => 'Iraqi',
            92 => 'Irish',
            93 => 'Israeli',
            94 => 'Italian',
            95 => 'Ivorian',
            96 => 'Jamaican',
            97 => 'Japanese',
            98 => 'Jordanian',
            99 => 'Kazakhstani',
            100 => 'Kenyan',
            101 => 'Kittian and Nevisian',
            102 => 'Kuwaiti',
            103 => 'Kyrgyz',
            104 => 'Laotian',
            105 => 'Latvian',
            106 => 'Lebanese',
            107 => 'Liberian',
            108 => 'Libyan',
            109 => 'Liechtensteiner',
            110 => 'Lithuanian',
            111 => 'Luxembourger',
            112 => 'Macedonian',
            113 => 'Malagasy',
            114 => 'Malawian',
            115 => 'Malaysian',
            116 => 'Maldivan',
            117 => 'Malian',
            118 => 'Maltese',
            119 => 'Marshallese',
            120 => 'Mauritanian',
            121 => 'Mauritian',
            122 => 'Mexican',
            123 => 'Micronesian',
            124 => 'Moldovan',
            125 => 'Monacan',
            126 => 'Mongolian',
            127 => 'Moroccan',
            128 => 'Mosotho',
            129 => 'Motswana',
            130 => 'Mozambican',
            131 => 'Namibian',
            132 => 'Nauruan',
            133 => 'Nepalese',
            134 => 'New Zealander',
            135 => 'Nicaraguan',
            136 => 'Nigerian',
            137 => 'Nigerien',
            138 => 'North Korean',
            139 => 'Norwegian',
            140 => 'Omani',
            141 => 'Pakistani',
            142 => 'Palauan',
            143 => 'Panamanian',
            144 => 'Papua New Guinean',
            145 => 'Paraguayan',
            146 => 'Peruvian',
            147 => 'Polish',
            148 => 'Portuguese',
            149 => 'Qatari',
            150 => 'Romanian',
            151 => 'Russian',
            152 => 'Rwandan',
            153 => 'Saint Lucian',
            154 => 'Salvadoran',
            155 => 'Samoan',
            156 => 'San Marinese',
            157 => 'Sao Tomean',
            158 => 'Saudi',
            159 => 'Senegalese',
            160 => 'Serbian',
            161 => 'Seychellois',
            162 => 'Sierra Leonean',
            163 => 'Singaporean',
            164 => 'Slovakian',
            165 => 'Slovenian',
            166 => 'Solomon Islander',
            167 => 'Somali',
            168 => 'South African',
            169 => 'South Korean',
            170 => 'Spanish',
            171 => 'Sri Lankan',
            172 => 'Sudanese',
            173 => 'Surinamer',
            174 => 'Swazi',
            175 => 'Swedish',
            176 => 'Swiss',
            177 => 'Syrian',
            178 => 'Taiwanese',
            179 => 'Tajik',
            180 => 'Tanzanian',
            181 => 'Thai',
            182 => 'Tobagonian',
            183 => 'Togolese',
            184 => 'Tongan',
            185 => 'Trinidadian',
            186 => 'Tunisian',
            187 => 'Turkish',
            188 => 'Tuvaluan',
            189 => 'Ugandan',
            190 => 'Ukrainian',
            191 => 'Uruguayan',
            192 => 'Uzbekistani',
            193 => 'Venezuelan',
            194 => 'Vietnamese',
            195 => 'Yemenite',
            196 => 'Zambian',
            197 => 'Zimbabwean'
        ]
    ]



];
